# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-create_time'], 'verbose_name': '游戏', 'verbose_name_plural': '游戏'},
        ),
        migrations.AlterModelOptions(
            name='gamequestion',
            options={'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='测试', max_length=50, verbose_name='游戏名称'),
            preserve_default=False,
        ),
    ]
