# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180305_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_over',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, verbose_name='游戏状态'),
        ),
    ]
