# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180306_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, editable=False, verbose_name='游戏状态'),
        ),
    ]
