# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_gameresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'verbose_name': '游戏排名', 'verbose_name_plural': '游戏排名'},
        ),
        migrations.AlterModelTable(
            name='gameresult',
            table='game_result',
        ),
    ]
