# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180306_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Game'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='join_time',
            field=models.DateTimeField(verbose_name='加入时间'),
        ),
    ]
