# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20180306_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='答对题数'),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='quiz.Game', verbose_name='游戏'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, verbose_name='题目'),
        ),
    ]
